# Defined here instead of devcontainer.json so Renovate can update the tag
FROM ghcr.io/nisheretail/devcontainers/nvm-ngrok:latest@sha256:e1b6825c08fb79ed2a1effa658aa330430c00397d4bca52ad3d59f17b1842b7e
